language: ruby

matrix:
  include:
    - dist: xenial
      env: DIST=xenial
    - dist: bionic
      env: DIST=bionic

install: true
script: 
  - time ruby demo.rb &
  - time ruby demo.rb &
  - wait

notifications:
  email: false
