rvm:
  - 2.6

env:
  - FOO=foo

script: echo $FOO

jobs:
  include:
    - stage: deploy
      script:
      # Keep in mind to overwrite these here
      - cat /proc/cpuinfo
      - free -m
      rvm: 
        - 2.3
        - 2.6.3
      env: 
        - FOO=foo1
        - FOO=foo2
